dist: xenial

matrix:
  include:
    - &js
      name: JS - Babel Plugin
      language: node_js
      node_js: '9'
      install:
        - cd babel-plugin
        - npm install
      script:
        - npm run test
        - npm run eslint
    - <<: *js
      name: JS - URL Builder
      install:
        - cd client
        - npm install
    - &py
      name: Python 2.7 - Flask Plugin
      language: python
      python: 2.7
      install:
        - pip install -e flask-cli/
        - pip install -r requirements.dev.txt
      script:
        - isort -rc --diff --check-only flask-cli/
        - pycodestyle --max-line-length 100 flask-cli/
        - pytest flask-cli/
    - <<: *py
      name: Python 3.5 - Flask Plugin
      python: 3.5
    - <<: *py
      name: Python 3.6 - Flask Plugin
      python: 3.6
    - <<: *py
      name: Python 3.7 - Flask Plugin
      python: 3.7

notifications:
  email: false
  irc:
    channels:
      - 'chat.freenode.net#indico'
    use_notice: true
    skip_join: true
